; ============================================================
;  IoMT firmware — ESP32 + DHT11 -> AWS IoT Core (MQTT/TLS)
;  PlatformIO auto-installs the libraries listed in lib_deps.
; ============================================================
[env:esp32dev]
platform = espressif32
board = esp32dev            ; generic ESP32 DevKit; change if you have S3/C3/etc.
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; If upload/monitor can't find your board automatically on Windows,
; uncomment and set your COM port (check Device Manager):

upload_port = COM3
monitor_port = COM3
